apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: bank-of-hamburg
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: bank-of-hamburg
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: bank-of-hamburg
        tier: backend
    spec:
      containers:
      - name: go-backend
        image: gcr.io/hacker-playground/account-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key:  redis.port
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
