apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: bank-of-hamburg
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: bank-of-hamburg
    tier: backend
