apiVersion: v1
kind: Pod
metadata:
  name: bank-of-hamburg
  labels:
    app: bank-of-hamburg
spec:
  containers:
  - name: bank-of-hamburg
    image: gcr.io/hacker-playground/hacker-playground:trigger
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 30
    readinessProbe:
      httpGet:
        path: /readiness
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 30
